### ISSUE TITLE
Speed up outliers-per-threshold script

### ISSUE THREAD

**Issue by snim2** [softdevteam/warmup_experiment#151]
The outlier-per-threshold script takes a long time to run (around 1 hour on bencher2). It canot run with pypy, so the sensible way to improve its running time would be to use `multiprocessing` to parallelise the data collection work. Alternatively, we could cache the collected data in a JSON file, and allow the user the choice of recomputing it, or reading it back from the cached file.

**Comment by ltratt** [comment]
Have we profiled the program? Naively, I wondered if there's an accidental O(n^2) chunk lurking somewhere that might be excised?

**Comment by snim2** [comment]
There are nested loops, but they aren't accidental :) The algorithm looks like this:

```
for each window size 
    for each threshold
        read the entire data set and calculate outliers for all 450 run sequences
```

I don't think you can save any useful data between window sizes and thresholds (and I wouldn't be very keen to do so, in case we made a mistake with the maths), so everything is calculated from scratch.

Potentially you could compute the windows for the largest window size first, then shrink them down, but that sounds like a recipe for off-by-n errors to me.

I don't think the charting takes an especially long time, and I don't think matplotlib is thread-safe anyhow, so the data collection is the important part here.

**Comment by ltratt** [comment]
I profiled things, and it looks like pretty much all the time is spent in numpy:

```
Mon Sep  5 09:49:58 2016    times

         267941881 function calls (267934723 primitive calls) in 304.965 seconds

   Ordered by: internal time
   List reduced from 4619 to 10 due to restriction <10>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
  8100000   75.167    0.000  148.861    0.000 _methods.py:73(_var)
 24304996   47.277    0.000   47.277    0.000 {method 'reduce' of 'numpy.ufunc' objects}
 24306569   39.374    0.000   39.374    0.000 {numpy.core.multiarray.array}
     4050   29.700    0.007  304.004    0.075 plot_outliers_by_threshold.py:228(get_all_outliers)
  8100001   22.576    0.000   77.671    0.000 _methods.py:49(_mean)
  8100000   19.450    0.000  171.026    0.000 _methods.py:119(_std)
 16200001   15.073    0.000   19.629    0.000 _methods.py:39(_count_reduce_items)
  8100000   11.817    0.000   89.488    0.000 fromnumeric.py:2632(mean)
  8100000    9.902    0.000  180.928    0.000 fromnumeric.py:2718(std)
 24302114    8.348    0.000   47.716    0.000 numeric.py:462(asanyarray)
```

Multiprocessing isn't a great solution, because at most we're going to get a Nx increase (where N is the number of cores). There are a couple of obvious solutions, both of which involve a pre-processing step. I suggest that for each `json.bz2` file, `plot_outliers_by_threshold` creates a `.cache` file with a pre-processed version of the output. From the user's point of view, they won't care if pre-processing has occurred or not.

The most obvious is to try using PyPy's numpy fork. I quickly tried that, and it doesn't seem to implement `mean` or `std` in the top-level module. However, both are easy functions that can be implemented in normal Python, and should then be merrily munched by PyPy.

If that fails, or is too slow, we could rewrite the data processing in Rust. That should run pretty fast with `--release` ;)

**Comment by ltratt** [comment]
[BTW, here's the PyPy numpy status page http://buildbot.pypy.org/numpy-status/latest.html]

**Comment by snim2** [comment]
OK, that sounds like it'll do the job. We no longer use `mean` and `std`, but we do use `median` and `percentile` which seem to be passing the tests on the status page.

I'll give this a go when I've cleared other tasks.

**Comment by ltratt** [comment]
OK, I was running on master which still use `mean` and `std`. Reimplementing `median` and `percentile` would also be fairly easy, if it turns out to be necessary. In a sense, it might be better to do that, as installing PyPy + numpy is a real pain in the rear end. If we keep to "pure" Python, then we can just rely on the user installing pypy (which is fairly easy).

**Comment by ltratt** [comment]
[I just hacked up a quick variant of mean/stddev in pure Python, ran them in PyPy, and the data-processing became 90x faster. Which I think would be good enough ;)]

**Comment by snim2** [comment]
Wow. Well, I'll save a chart from the next run to diff against as a test, then have a go at an implementation.

**Comment by snim2** [comment]
Just to be pedantically clear, when you wrote the faster version of mean/std for PyPy, you didn't place that code inside the `plot_outlier_by_threshold.py` script?

**Comment by ltratt** [comment]
I did. [I just wrote the obvious Python versions -- nothing clever.]

**Comment by snim2** [comment]
Ah, so you must have persuaded PyPy to import `seaborn` and `matplotlib`, which is the thing I failed to do. How did you manage it?

**Comment by ltratt** [comment]
I just disabled those. I think that you'll need to make the data-processing a separate script which can be run by PyPy and produces a pre-processed cache file.

**Comment by snim2** [comment]
OK, that sounds good to me.
