### ISSUE TITLE
Each script that needs it should set LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by snim2** [softdevteam/warmup_experiment#430]
The user needs to add:

```bash
export LD_LIBRARY_PATH=.../work/R-inst/lib/R/lib:$LD_LIBRARY_PATH
```

to `.bashrc` or equivalent.

**Comment by ltratt** [comment]
Why can't we do this automatically e.g. with a wrapper? Expecting users to do this is pretty nasty :(

**Comment by snim2** [comment]
You mean have each script that needs `LD_LIBRARY_PATH` export it before it runs?

**Comment by snim2** [comment]
Actually I see we have done this in some scripts but not all. Hmmm.

**Comment by ltratt** [comment]
Aha, sounds good (and not to hard if we've done it before!).

**Comment by ltratt** [comment]
So the way we do this in some Python scripts with `os.environ` doesn't seem to work. I suspect we need to add a wrapper. At the moment `./build_stats.sh` exports `LD_LIBRARY_PATH` globally (which, IMHO, it should not do), so if you run scripts in the same terminal as you built things in, they seem to work. Otherwise you get weird errors about `.so` files not being found.

**Comment by snim2** [comment]
This may need updating, to match changes in warmup_stats.

**Comment by snim2** [comment]
I'll be looking again at this in the next couple of days...
