### ISSUE TITLE
Build our own GCC and use throughout the build process.

### ISSUE THREAD

**Issue by vext01** [softdevteam/warmup_experiment#74]
Some VMs currently use the system GCC.

**Comment by ltratt** [comment]
Thinking about it a bit, I'd strengthen this slightly: we should set CC for every VM to a specific VM of our choosing, even on Linux. At the moment, for all we know, one VM builds with GCC and another with clang. If it works, I'd probably be inclined to build everything with clang on all platforms, because we can probably use the same version of the compiler more easily.

**Comment by vext01** [comment]
I was unaware of clang being in the mix.

**Comment by ltratt** [comment]
Off the top of my head, I can't remember if any of the VMs prefer clang or not. I don't really mind which compiler we use so long as we're consistent.

**Comment by vext01** [comment]
I agree that we should choose one C compiler, build it ourselves and force it.

**Comment by vext01** [comment]
As discussed with @ltratt, we will need to build our own GCC across all platforms, but since we are (for now) disregarding OpenBSD, and since the Debian machines use the same GCC, this will wait until after the draft paper is out.

**Comment by vext01** [comment]
This is done. Albeit, with PIE on OpenBSD. It's not clear if PIE can be disabled. Spoke with @ltratt and we are happy for now. Closing.
